xonas_proj/comps/urls.py
from django.urls import path
from . import views

app_name = 'comps'

urlpatterns = [
    path('', views.cats, name='cats'),
    path('force_upd/', views.force_upd, name='force_upd'),
    path('list8/<slug:category_slug>', views.cat_list8, name='list8'),
    path('list14/<slug:category_slug>', views.cat_list14, name='list14'),
    path('list21/<slug:category_slug>', views.cat_list21, name='list21'),
    path('list30/<slug:category_slug>', views.cat_list30, name='list30'),
    path('list/like', views.like_item, name='like'),
    path('del/<int:id>', views.del_item, name='like_del'),
    path('favorites/', views.favorites, name='favorites'),
]

xonas_proj/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
]

xonas_proj/reports/urls.py
from django.urls import path
from . import views

app_name = 'reports'

urlpatterns = [
    path('', views.reports, name='reports'),
]

xonas_proj/xonas_proj/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

urlpatterns = [
    path('', include('core.urls', namespace='core')),
    path('admin/', admin.site.urls),
    path('comps/', include('comps.urls', namespace='comps')),
    path('login/', auth_views.LoginView.as_view(), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('reports/', include('reports.urls', namespace='reports'))
]

xonas_proj/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© Xonas Project</p>    
</footer>

xonas_proj/templates/includes/header.html
{% load static %}
<header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
    <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
        <img src='https://static-basket-01.wb.ru/vol1/sellers/brands/9BB1150522FC33.webp'>
    </a>
    {% with request.resolver_match.view_name as view_name %}
    <ul class="nav nav-pills">
        {% if user.is_authenticated %}
        <li class="nav-item"><a href="{% url 'core:index' %}" class="nav-link {% if view_name == 'core:index' %} active {% endif %}" aria-current="page">Главная</a></li>
        <li class="nav-item"><a href="{% url 'comps:cats' %}" class="nav-link {% if view_name == 'comps:cats' %} active {% endif %}">Новинки</a></li>
        <li class="nav-item"><a href="{% url 'reports:reports' %}" class="nav-link {% if view_name == 'reports:reports' %} active {% endif %}">Отчеты</a></li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">{{ user.username }}</a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'comps:favorites' %}">Избранное</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'logout' %}">Выйти</a></li>
            </ul>
        </li>
        {% endif %}
    </ul>
    {% endwith %}
</header>

xonas_proj/templates/includes/item_card_simple.html
{% load static %}
<div class="col-6 col-md-4 my-1">
    <div class="card">
      <img 
        class="img-fluid card-img-top" 
        height="400" width="300"
        src="https:{{ item.thumb_middle }}"
      >
      <div class="card-body">           
        <h5 class="card-title">{{ item.name }} </h5>
        <p class="card-title">{{ item.brand }}</p>
        <p class="card-title">{{ item.sku_first_date }}</p>
        
        <div class="card-img-overlay">
          <a href="https://www.wildberries.ru/catalog/{{ item.sku_id }}/detail.aspx" class="btn btn-info">WB</a>
          <a href="https://mpstats.io/wb/item/{{ item.ssku_id }}" class="btn btn-info">MP</a>
        </div>
        <div class="card text-center">
          <a href="{% url 'comps:like_del' item.id  %}" class="btn btn-info">Удалить</a>
        </div>
      </div>
    </div>

</div>

xonas_proj/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
  <nav aria-label="Page navigation" class="my-5">
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
        <li class="page-item">
          <a class="page-link" href="{{ request.get_full_path }}?&page={{ page_obj.previous_page_number }}">
            <<
          </a>
        </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% elif i >= page_obj.number|add:-2 and i <= page_obj.number|add:2  %}
          <li class="page-item">
            <a class="page-link" href="{{ request.get_full_path }}?&page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="{{ request.get_full_path }}?&page={{ page_obj.next_page_number }}">
            >>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="{{ request.get_full_path }}?&page={{ page_obj.paginator.num_pages }}">
            Последняя
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

xonas_proj/templates/includes/trend_card.html
{% load static %}
{% load comps_extras %}
<div class="col-6 col-md-4 my-1">
    <div class="card" id="{{ item.sku_id }}">
      <img 
        class="img-fluid card-img-top" 
        height="400" width="300"
        src="https:{{ item.thumb_middle }}"
      >
      <div class="card-body">           
        <h5 class="card-title">{{ item.name }} </h5>
        <p class="card-title">{{ item.brand }}</p>
        <p class="card-title">{{ item.sku_first_date }}</p>
        <p class="card-title">Выручка: {{ item.revenue }} руб.</p>
        <p class="card-title">Оборачиваемость: {{ item.turnover_days }} д.</p>
        <div class="card-img-overlay">
          <h3><span class="badge bg-primary">{{ item.median_price }} p.</span></h3>
          {% if item.stocks == True %}
            <h4><span class="badge bg-success">Остатки</span></h4>
          {% endif %}
          {% if item.avg_sells_growth  == True %}
            <h4><span class="badge bg-success">Рост среднего</span></h4>
          {% endif %}
          {% if item.fix_avg  == True %}
            <h4><span class="badge bg-warning">Фикс. среднее</span></h4>
          {% endif %}
          <a href="https://www.wildberries.ru/catalog/{{ item.sku_id }}/detail.aspx" class="btn btn-info">WB</a>
          <a href="https://mpstats.io/wb/item/{{ item.sku_id }}" class="btn btn-info">MP</a>
          <div>
            
          </div>
        </div>
      </div>
      <div class="card text-center">
        {% if item.sku_id in likes %}
        <a href="#" class="btn btn-secondary disabled">В избранном</a>
        {% else %}
        <a href="{% url 'comps:like' %}?id={{ item.id }}" class="btn btn-info">В избранное</a>
        {% endif %}
        <div>
          <canvas id="myChart{{ item.sku_id }}" width="10" height="3"></canvas>
        </div>
        <div>
          <canvas id="myChartY{{ item.sku_id }}" width="10" height="3"></canvas>
        </div>
      </div>   
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
      
      <script>
        var ctx = document.getElementById('myChart' + {{ item.sku_id }});
        new Chart(ctx, {
          type: 'bar',
          data: {
            datasets: [{
              label: 'Продажи',
              data: {{ item.sells_list|get_graph }},
              borderWidth: 1
            }],
            labels: {{ dts|safe }},
          },
          options: {
            scales: {
              y: {
                beginAtZero: true
              }
            }
          }
        });

        var ctx2 = document.getElementById('myChartY' + {{ item.sku_id }});
        new Chart(ctx2, {
          type: 'bar',
          data: {
            datasets: [{
              label: 'Остатки',
              data: {{ item.stocks_list|get_graph }},
              borderWidth: 1
            }],
            labels: {{ dts|safe }},
          },
          options: {
            scales: {
              y: {
                beginAtZero: true
              }
            }
          }
        });
      </script>
</div>